add_test( [==[DFS maintains the deepest point on top]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS maintains the deepest point on top]==]  )
set_tests_properties( [==[DFS maintains the deepest point on top]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS maintains a depth-first ordering]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS maintains a depth-first ordering]==]  )
set_tests_properties( [==[DFS maintains a depth-first ordering]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS maintains the correct point on top]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS maintains the correct point on top]==]  )
set_tests_properties( [==[BFS maintains the correct point on top]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS maintains the BFS ordering]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS maintains the BFS ordering]==]  )
set_tests_properties( [==[BFS maintains the BFS ordering]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS iterator starts at the start point]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS iterator starts at the start point]==]  )
set_tests_properties( [==[DFS iterator starts at the start point]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS visits the correct pixel first]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS visits the correct pixel first]==]  )
set_tests_properties( [==[DFS visits the correct pixel first]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS iterator starts at the start point]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS iterator starts at the start point]==]  )
set_tests_properties( [==[BFS iterator starts at the start point]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS visits the correct pixel first]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS visits the correct pixel first]==]  )
set_tests_properties( [==[BFS visits the correct pixel first]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS visits all points within a tolerance]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS visits all points within a tolerance]==]  )
set_tests_properties( [==[DFS visits all points within a tolerance]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS visits all points within a tolerance]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS visits all points within a tolerance]==]  )
set_tests_properties( [==[BFS visits all points within a tolerance]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS visits all points within a tolerance (includes pixels on image edge)]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS visits all points within a tolerance (includes pixels on image edge)]==]  )
set_tests_properties( [==[DFS visits all points within a tolerance (includes pixels on image edge)]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS visits all points within a tolerance (includes pixels on image edge)]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS visits all points within a tolerance (includes pixels on image edge)]==]  )
set_tests_properties( [==[BFS visits all points within a tolerance (includes pixels on image edge)]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS iterator visits all points in the correct order]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS iterator visits all points in the correct order]==]  )
set_tests_properties( [==[DFS iterator visits all points in the correct order]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS iterator visits all points in the correct order]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS iterator visits all points in the correct order]==]  )
set_tests_properties( [==[BFS iterator visits all points in the correct order]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[DFS iterator visits all points in the correct order (7x4 image)]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[DFS iterator visits all points in the correct order (7x4 image)]==]  )
set_tests_properties( [==[DFS iterator visits all points in the correct order (7x4 image)]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[BFS iterator visits all points in the correct order (7x4 image)]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[BFS iterator visits all points in the correct order (7x4 image)]==]  )
set_tests_properties( [==[BFS iterator visits all points in the correct order (7x4 image)]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[Illini I - FloodFilledImage - DFS]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[Illini I - FloodFilledImage - DFS]==]  )
set_tests_properties( [==[Illini I - FloodFilledImage - DFS]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( Speedtest /workspaces/cs225/newRepo/mp_traversals/build_time/test Speedtest  )
set_tests_properties( Speedtest PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[Illini I - FloodFilledImage - BFS]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[Illini I - FloodFilledImage - BFS]==]  )
set_tests_properties( [==[Illini I - FloodFilledImage - BFS]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[Lantern - FloodFilledImage - BFS]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[Lantern - FloodFilledImage - BFS]==]  )
set_tests_properties( [==[Lantern - FloodFilledImage - BFS]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[PacMan - FloodFilledImage - DFS]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[PacMan - FloodFilledImage - DFS]==]  )
set_tests_properties( [==[PacMan - FloodFilledImage - DFS]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
add_test( [==[PacMan - FloodFilledImage - BFS]==] /workspaces/cs225/newRepo/mp_traversals/build_time/test [==[PacMan - FloodFilledImage - BFS]==]  )
set_tests_properties( [==[PacMan - FloodFilledImage - BFS]==] PROPERTIES WORKING_DIRECTORY /workspaces/cs225/newRepo/mp_traversals/build_time)
set( test_TESTS [==[DFS maintains the deepest point on top]==] [==[DFS maintains a depth-first ordering]==] [==[BFS maintains the correct point on top]==] [==[BFS maintains the BFS ordering]==] [==[DFS iterator starts at the start point]==] [==[DFS visits the correct pixel first]==] [==[BFS iterator starts at the start point]==] [==[BFS visits the correct pixel first]==] [==[DFS visits all points within a tolerance]==] [==[BFS visits all points within a tolerance]==] [==[DFS visits all points within a tolerance (includes pixels on image edge)]==] [==[BFS visits all points within a tolerance (includes pixels on image edge)]==] [==[DFS iterator visits all points in the correct order]==] [==[BFS iterator visits all points in the correct order]==] [==[DFS iterator visits all points in the correct order (7x4 image)]==] [==[BFS iterator visits all points in the correct order (7x4 image)]==] [==[Illini I - FloodFilledImage - DFS]==] Speedtest [==[Illini I - FloodFilledImage - BFS]==] [==[Lantern - FloodFilledImage - BFS]==] [==[PacMan - FloodFilledImage - DFS]==] [==[PacMan - FloodFilledImage - BFS]==])
